---
title: "Kenya EDA"
author: "Amber Lee"
date: "1/19/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```

```{r packages}
library(tidytuesdayR)
library(tidyverse)
# install.packages("remotes")
# remotes::install_github("Shelmith-Kariuki/rKenyaCensus")
library(rKenyaCensus) # this loads data
# data(package = "rKenyaCensus")

# need tmaptools and stars package 
# install.packages(c("tmaptools", "stars", "tmap"))
library(tmap)
library(sf)
```

```{r load data}

tuesdata <- tidytuesdayR::tt_load('2021-01-19')

counties <- rKenyaCensus::KenyaCounties_SHP
crops <- tuesdata$crops
```

# Viz

Percentage of internet use in Kenya

```{r}

internet <- rKenyaCensus::V4_T2.33 %>%
  filter(AdminArea == "County") %>%
  select(-SubCounty, -AdminArea)

counties_sf <- st_as_sf(counties)

internet_sf <- merge(counties_sf, internet, by = "County")

tm_shape(internet_sf) + 
  tm_polygons(col = "UoI_Total_Perc") +
  tm_layout(title = "\n Percentage of Internet Use in Kenyan Counties \n",
            inner.margins = c(0.1, 0.1, 0.1, 0.1))
```

Tidying crops 

```{r}

crops <- crops %>%
  filter(SubCounty != "KENYA") %>%
  rename(County = SubCounty) %>%
  mutate(countNA = rowSums(is.na(.))) %>%
  select(-Farming)

topcrops <- crops %>%
  rename(Khat = `Khat (Miraa)`) %>%
  select(-countNA) %>%
  pivot_longer(cols = Tea:Khat, 
               names_to = "cropType",
               values_to = "population") %>%
  arrange(County, -population) %>%
  group_by(County) %>%
  top_n(1) %>%
  ungroup()

```

```{r}
topcrops_sf <- merge(counties_sf, topcrops, by = "County")

tm_shape(topcrops_sf) + 
  tm_polygons(col = "cropType") +
  tm_layout(title = "Most grown crop per county in Kenya",
            title.size = 1,
            title.position = c("left", "top"),
            legend.title.size = 0.8,
            legend.title.fontface = "bold",
            inner.margins = c(0.1, 0.1, 0.1, 0.1))

```
```{r}
citation('rKenyaCensus')
```

