---
title: "tate museum 01-12"
author: "Amber Lee"
date: "1/12/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```

```{r packages}
library(tidytuesdayR)
library(tidyverse)
library(countrycode)

```

```{r load data}
tuesdata <- tidytuesdayR::tt_load('2021-01-12')

artist <- tuesdata$artists
artwork <- tuesdata$artwork

```

# exploration

gender and date of birth for artist: 

```{r}

ggplot(data = artist, aes(x = yearOfBirth)) +
  geom_density(aes(fill = gender)) +
  facet_wrap(~ gender)
  
ggplot(data = artist, aes(x = yearOfBirth)) +
  geom_density(aes(color = gender))
```

levels of artwork variables

```{r}

artwork %>% 
  group_by(artistRole) %>%
  summarize(count = n())

artwork %>% distinct(medium)

artwork_after <- artwork %>% 
  filter(artistRole == "after") %>%
  rename(artworkId = id,
         id = artistId)
```

can join different datasets together

```{r}

artwork %>% 
  rename(artworkId = id,
         id = artistId) %>%
  left_join(artist, by = "id")

```

```{r}

placeOfBirth <- artist %>%
  distinct(placeOfBirth) %>%
  pull()

artist <- artist %>%
  separate(placeOfBirth, c("cityBirth", "countryBirth"), 
           sep = ", ", fill = "left") %>%
  separate(placeOfDeath, c("cityDeath", "countryDeath"),
           sep = ", ", fill = "left")

# plots for when each country/year combo has at least 2 artists

artist %>%
  group_by(countryBirth, yearOfBirth) %>%
  summarize(count = n()) %>%
  filter(count > 2) %>%
  ggplot() +
  geom_density(aes(x = yearOfBirth, color = countryBirth))
  
artist %>%
  group_by(countryBirth, yearOfBirth) %>%
  summarize(count = n()) %>%
  filter(count > 2) %>%
  ggplot() +
  geom_boxplot(aes(x = countryBirth, y = yearOfBirth))

```
```{r}

# plot when there are at least 10 artists per countrybirth 

artist %>% 
  group_by(countryBirth) %>% 
  mutate(count = n()) %>% 
  filter(count >=10) %>%
  ungroup %>%
  ggplot(mapping = aes(x = countryBirth, y = yearOfBirth)) + 
  geom_boxplot()

```

question: what countries of birth (for artists) are represented in the museum artwork? where are the pieces of art frequently from?

```{r}

artist_places <- artist %>%
  select(cityBirth, countryBirth, cityDeath, countryDeath, id) %>%
  rename(artistId = id)

artwork_places <- artwork %>%
  left_join(artist_places, by = "artistId")

artwork_places %>%
  group_by(countryBirth) %>%
  mutate(count = n()) %>%
  distinct(countryBirth, count) %>%
  arrange(-count) %>%
  head(10)


# when plotting, remove UK and US because we see those are highly represented!

artwork_places %>%
  group_by(countryBirth) %>%
  summarize(count = n()) %>%
  filter(count > 50 & countryBirth != "United Kingdom" &
           countryBirth != "United States" &
           countryBirth != "Deutschland") %>%
  ggplot() +
  geom_bar(aes(x = countryBirth, y = count), stat = "identity") +
  coord_flip() +
  labs(title = "number of artworks from lesser-represented countries",
       subtitle = "removing UK, US, and Germany")

```

do artists migrate? do artists usually die in the country where they are born?


```{r}
# 
# artist_places %>%
#   mutate(samecountry = case_when(countryBirth == countryDeath ~ TRUE,
#                                  countryBirth != countryDeath ~ FALSE)) %>%
#   group_by(countryBirth, samecountry) %>%
#   summarize(count = n()) %>%
#   spread(key = samecountry, value = count, fill = 0) %>%
#   rename(differentcountry = `FALSE`, 
#          samecountry = `TRUE`) %>%
#   filter(differentcountry > 0 & samecountry > 0) %>%
#   mutate(total = differentcountry + samecountry + `<NA>`,
#          rate_same = samecountry / total, 
#          rate_NA = `<NA>` / total) %>%
#   ggplot(aes(x = countryBirth, y = rate_same, fill = rate_NA)) +
#   geom_bar(stat = "identity") +
#   coord_flip() +
#   labs(title = "rate of artists, per country, whose birth and death country are the same")


artist_places %>%
  mutate(samecountry = case_when(countryBirth == countryDeath ~ TRUE,
                                 countryBirth != countryDeath ~ FALSE)) %>%
  group_by(countryBirth, samecountry) %>%
  summarize(count = n()) %>%
  filter(count > 5) %>%
  ggplot(aes(x = countryBirth, y = count, fill = samecountry)) +
  geom_bar(position = "fill", stat = "identity") +
  coord_flip()

```

